management:
    endpoints:
        web:
            exposure:
                include: openapi, swagger-ui

spring:
    batch:
        job:
            enabled: false
    flyway:
#        enabled: false
        baseline-on-migrate: true
        locations: classpath:migrations
    http:
        multipart:
            max-file-size: 18MB
            max-request-size: 20MB
    jms:
        cache:
            enabled: false
    main:
        allow-bean-definition-overriding: false

    jackson:
#        serialization:
#            fail-on-empty-beans: false
        jackson:
            default-property-inclusion: always
        deserialization:
            fail-on-unknown-properties: false
        mapper:
          auto-detect-fields: true
        visibility:
            all: any

## Springdoc ##
openapi:
    info:
        license:
            name: Apache License, Version 2.0
            url: https://www.apache.org/licenses/LICENSE-2.0

springdoc:
    group-configs[0]:
        group: catalogue
        display-name: Data Catalogue
        packages-to-scan:
            - eu.intelcomp
            - gr.athenarc.catalogue.controller
    group-configs[1]:
        group: catalogue-lib
        display-name: Catalogue Library
        packages-to-scan:
            - gr.athenarc.catalogue
    group-configs[2]:
        group: registry
        display-name: Registry Core
        packages-to-scan:
            - eu.openminted

    swagger-ui:
        doc-expansion: none
        operations-sorter: method
        path: /swagger-ui.html
        syntax-highlight:
            activated: false
            theme: obsidian
        tags-sorter: alpha
        version: 3

## Logging ##
logging:
    level:
        root: INFO

## Registry Properties ##
hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
    format_sql: false
    hbm2ddl.auto: update

## Elastic Properties ##
elastic:
    index.max_result_window: 10000
    aggregation:
        topHitsSize: 100
        bucketSize: 100
