spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1081667473465-s1g236hvbh3m7rniptoqtfktboees0rh.apps.googleusercontent.com
            client-secret: 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
          #            scope:
          #              - openid
          #              - email
          #              - profile
          cite:
            client-id: intelcomp-process-mgmt
            client-secret: c17a579a-5246-4949-9e86-21e92cc2e381
            redirect-uri: http://localhost:8080/auth/realms/appsdeveloperblog/protocol/openid-connect/auth
            scope:
              - openid
              - email
              - profile

        provider:
          cite:
            issuer-uri: https://gatekeeper.cite.gr/auth/realms/testdev
  #            authorization-uri: https://aai.eosc-portal.eu/oidc/authorize
  #            token-uri: https://aai.eosc-portal.eu/oidc/token
  #            jwk-set-uri: https://aai.eosc-portal.eu/oidc/jwk
  #            user-info-uri: https://aai.eosc-portal.eu/oidc/userinfo
  #            user-name-attribute: sub


  redis:
    host: vereniki.athenarc.gr
    port: 6379
    password: redis13031992k

server:
  servlet:
    contextPath: /intelcomp

logging:
  level:
    org.springframework.security.: DEBUG
    org.springframework.security.web.util.: INFO
    org.springframework.web.client.RestTemplate: DEBUG
    org.reflections.Reflections: WARN

intelcomp:
  frontBaseUrl: http://localhost:4200
  loginRedirect: ${frontBaseUrl}
  logoutRedirect: ${frontBaseUrl}
  admins:
    #    - spyroukon@gmail.com
    - stefania.martziou@gmail.com